version: "3"
services:
  mongodb:
    image: mongo:4.2.1
    container_name: "mongodb"
    ports:
    - 27017:27017
  backend:
    build: .
    ports:
    - 8080:8080
    links:
    - mongodb
    container_name: "backend"