version: "3"
services:
  raptorsapp-database:
    container_name: "raptorsapp-database"
    image: mongo:4.2.1
    ports:
    - 27017:27017
  raptorsapp-backend:
    container_name: "raptorsapp-backend"
    build: ./raptorsapp-backend/
    ports:
    - 8080:8080
    links:
    - raptorsapp-database